# Generated by Django 3.2.3 on 2021-05-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='material',
            field=models.CharField(default='', max_length=40),
        ),
    ]
