# Generated by Django 3.2.3 on 2021-10-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_clothing_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=19.99, max_digits=4),
        ),
        migrations.AddField(
            model_name='clothingtype',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
