# Generated by Django 3.2.3 on 2021-10-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20211012_2212'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collection_logo',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
