# Generated by Django 3.2.3 on 2021-11-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_clothingtype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='stripe_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
