# Generated by Django 3.2.3 on 2021-11-09 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20211109_1410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothing',
            name='preview_image_back',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='clothing',
            name='preview_image_live',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
