# Generated by Django 3.2.3 on 2021-11-24 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20211109_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='printify_product_id',
            field=models.CharField(default='', max_length=50),
        ),
    ]
